/* Generated By:JJTree: Do not edit this line. ASTExp4.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExp4 extends SimpleNode {
  public ASTExp4(int id) {
    super(id);
  }

  public ASTExp4(SLP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=991790bc95e8f0c1dee9ecb306d9eff4 (do not edit this line) */
