/* Generated By:JJTree: Do not edit this line. ASTVarAssign.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarAssign extends SimpleNode {
  public ASTVarAssign(int id) {
    super(id);
  }

  public ASTVarAssign(SLP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SLPVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2a078d12f3e5c54e67e7822c3ddae388 (do not edit this line) */
