/* Generated By:JavaCC: Do not edit this line. SLPTreeConstants.java Version 7.0.13 */
public interface SLPTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTATEMENTS = 1;
  public int JJTVOID = 2;
  public int JJTPRINTLN = 3;
  public int JJTVARASSIGN = 4;
  public int JJTEXP = 5;
  public int JJTEXP4 = 6;
  public int JJTEXP9 = 7;
  public int JJTEXP11 = 8;
  public int JJTEXP16 = 9;
  public int JJTNUMBER = 10;
  public int JJTVARIABLE = 11;


  public String[] jjtNodeName = {
    "Start",
    "Statements",
    "void",
    "Println",
    "VarAssign",
    "Exp",
    "Exp4",
    "Exp9",
    "Exp11",
    "Exp16",
    "Number",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=b9eabced9f545695f12937a374daea42 (do not edit this line) */
