/* Generated By:JavaCC: Do not edit this line. SLPVisitor.java Version 7.0.13 */
public interface SLPVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTStatements node, Object data);
  public Object visit(ASTPrintln node, Object data);
  public Object visit(ASTVarAssign node, Object data);
  public Object visit(ASTExp node, Object data);
  public Object visit(ASTExp4 node, Object data);
  public Object visit(ASTExp9 node, Object data);
  public Object visit(ASTExp11 node, Object data);
  public Object visit(ASTExp16 node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTVariable node, Object data);
}
/* JavaCC - OriginalChecksum=f629916484066e458902f0bcf6670c21 (do not edit this line) */
